name: CI

on:
  push:
    branches:
      - master
      - "hotfix/**"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.1", "3.2" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.233.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Build Assets
        run: |
          npm ci
          npm run build

      - name: Test Site
        run: bash tools/test.sh
