name: CI

on:
  push:
    branches: [master, "hotfix/**"]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:

jobs:
  build:
    # prebuilt Ruby + npm LTS가 모두 준비돼 있는 공식 이미지
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # posts 의 lastmod 계산용

      - name: Setup Ruby (3.2)
        # 24.04 인식 버그 패치 포함 최신 릴리스 고정
        uses: ruby/setup-ruby@v1.233.0
        with:
          ruby-version: 3.2          # 3.2.x 최신
          bundler-cache: true        # Gemfile.lock 기반 캐싱

      - name: Setup Node (LTS 20)
        uses: actions/setup-node@v4
        with:
          node-version: 20           # LTS 고정이 재현성에 안전
          cache: npm

      - name: Install & Build Front-assets
        run: |
          npm ci
          npm run build

      - name: Run Site Tests
        run: bash tools/test.sh
